---
name: Update product charts and overview document

on:
  # Manual button in Github.
  workflow_dispatch:
  # Run on a schedule.
  schedule:
    - cron: 46 5 * * *

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        # https://github.com/actions/checkout
        uses: actions/checkout@v4

      - name: Install UV
        run: |-
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "UV_SYSTEM_PYTHON=1" >> $GITHUB_ENV

      - name: Install Python
        # https://github.com/actions/setup-python
        # Will install python version from .python-version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python packages
        run: |-
          make install

      - name: Generate product charts
        shell: bash
        run: |-
          python main.py generate-graphs data/archive.json docs/charts/

      - name: Update overview document
        shell: bash
        run: |-
          python main.py generate-overview data/archive.json docs/charts/ docs/overview.md

      - name: Commit and push any new charts
        shell: bash
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add docs/charts/ docs/overview.md
          git commit -m "Update product charts" || exit 0
          git push
