name: Update price archive

on:
  # Run on each push to master.
  push:
    branches:
      - master
  # Manual button in Github.
  workflow_dispatch:
  # Run on a schedule.
  schedule:
    - cron: "46 4 * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        # https://github.com/actions/checkout
        uses: actions/checkout@v3

      - name: Install Python
        # https://github.com/actions/setup-python
        # Will install python version from .python-version
        uses: actions/setup-python@v4
        with:
          cache: "pip"

      - name: Install Python packages
        run: |-
          make install

      - name: Fetch latest data
        run: |-
          # Run price fetching and capture change summary (if there is one) into a file.
          python main.py update-price-archive data/products.json data/archive.json | tee commit_msg.txt

      - name: Generate timeline
        run: |-
          python main.py generate-timeline data/archive.json timeline.md

      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add data/archive.json
          git commit --file commit_msg.txt || exit 0
          git push
