name: Run tests and static analysis

on:
  # Run on each push.
  push:
  # Manual button in Github.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        # https://github.com/actions/checkout
        uses: actions/checkout@v3

      - name: Install Python
        # https://github.com/actions/setup-python
        # Will install python version from .python-version
        uses: actions/setup-python@v4
        with:
          cache: "pip"

      - name: Install Python packages
        run: |-
          make install

      - name: Check code is formatted with Black
        run: |-
          make black

      - name: Check code is formatted with isort
        run: |-
          make isort

      - name: Check code passes flake8 validation
        run: |-
          make flake8

      - name: Check code passes mypy validation
        run: |-
          make mypy

      - name: Check tests pass
        run: |-
          make test
